# Generated by Django 2.0.5 on 2018-06-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptowallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='execution_price',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
    ]
